const dexList = {
    "1inchSwap":'https://images.swft.pro/dex/1inch.png',
    "UniSwapV2":'https://images.swft.pro/dex/uniswap.png',
    "PancakeSwapV2":'https://images.swft.pro/dex/pancake.png',
    "MDexSwap":'https://images.swft.pro/dex/mdex.png',
    "PippiSwap":'https://images.swft.pro/dex/pippi.png',
    "LavaSwap":'',
    "SushiSwap":'https://images.swft.pro/dex/sushi.png',
    "DODOSwap":'https://images.swft.pro/dex/dodo.png',
    "O3Swap":'https://images.swft.pro/dex/o3.png',
    "ClassZZ":'https://images.swft.pro/dex/czz.png',
    "BinanceBridge":'https://images.swft.pro/inch1/0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c.png',
    "SWFT":"https://images.swft.pro/dex/SWFT.png",
    "CBridge":"https://images.swft.pro/dex/cBridge.png",
    "Orca":"https://www.orca.so/favicon-32x32.png",
    "Axie":"https://cdn.axieinfinity.com/landing-page/_next/static/images/logo-f3b5c962671a2516bc9fef42ad9e9145@1x.webp",
    "Cherryswap":"https://www.cherryswap.net/favicon.png",
    "Spookyswap":"https://spookyswap.finance/favicon.ico",
    "ArbSushiSwap":"https://images.swft.pro/dex/sushi.png",
    "Pangolin":"https://images.swft.pro/dex/Pangolin.png",
    "Traderjoe":"https://traderjoexyz.com/static/media/logo.bc60f78d.png",
    "bridgers1":"https://images.swft.pro/dex/bridgers1.png",
    "bridgers2":"https://images.swft.pro/dex/bridgers2.png",
}
export default dexList