export const supportNetWork = [
  {
    netWork: 'ETH',
    chainId: '1',
    symbol: 'ETH',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161',
    blockExplorerUrls: 'https://etherscan.io',
  },
  {
    netWork: 'BSC',
    chainId: '56',
    symbol: 'BNB',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://bscrpc.com',
    blockExplorerUrls: 'https://bscscan.com',
  },
  {
    netWork: 'HECO',
    chainId: '128',
    symbol: 'HT',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://http-mainnet.hecochain.com',
    blockExplorerUrls: 'https://hecoinfo.com',
  },
  {
    netWork: 'POLYGON',
    chainId: '137',
    symbol: 'MATIC',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://rpc-mainnet.maticvigil.com/',
    blockExplorerUrls: 'https://polygonscan.com',
  },
  {
    netWork: 'Polkadot',
    chainId: '000',
    symbol: 'DOT',
    decimals: 10,
    gasLimit: 400000,
    rpcUrl: 'wss://rpc.polkadot.io',
    blockExplorerUrls: 'https://polkadot.subscan.io',
  },
  {
    netWork: 'OKExChain',
    chainId: '66',
    symbol: 'OKT',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://exchainrpc.okex.org/',
    blockExplorerUrls: 'https://www.oklink.com/okexchain',
  },
  {
    netWork: 'ARB',
    chainId: '42161',
    symbol: 'ETH',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://arb1.arbitrum.io/rpc',
    blockExplorerUrls: 'https://arbiscan.io',
  },
  {
    netWork: 'TT',
    chainId: '108',
    symbol: 'TT',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://mainnet-rpc.thundercore.com',
    blockExplorerUrls: 'https://scan.thundercore.com',
  },
  {
    netWork: 'FTM',
    chainId: '250',
    symbol: 'FTM',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://rpc.ankr.com/fantom',
    blockExplorerUrls: 'https://ftmscan.com',
  },
  {
    netWork: 'AVAXC',
    chainId: '43114',
    symbol: 'AVAX',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://api.avax.network/ext/bc/C/rpc',
    blockExplorerUrls: 'https://cchain.explorer.avax.network',
  },
  {
    netWork: 'CELO',
    chainId: '42220',
    symbol: 'CELO',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://forno.celo.org',
    blockExplorerUrls: 'https://explorer.celo.org',
  },
  {
    netWork: 'ORC',
    chainId: '58',
    symbol: 'ONG',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://dappnode7.ont.io:10339',
    blockExplorerUrls: 'https://explorer.ont.io',
  },
  {
    netWork: 'SGB',
    chainId: '19',
    symbol: 'SGB',
    decimals: 18,
    gasLimit: 40000,
    rpcUrl: 'https://songbird.towolabs.com/rpc',
    blockExplorerUrls: 'https://songbird-explorer.flare.network',
  },
  {
    netWork: 'TRON',
    chainId: '0',
    blockExplorerUrls: 'https://tronscan.io/#',
  },
  {
    netWork: 'SOL',
    chainId: '2021',
    blockExplorerUrls: 'https://explorer.solana.com',
  },
  {
    netWork: 'LUNA',
    chainId: '1993',
    blockExplorerUrls: 'https://terra.stake.id/#',
  },
  {
    netWork: 'BTC',
    chainId: '1994',
    blockExplorerUrls: 'https://btc.com/btc',
  },
  {
    netWork: 'CRU',
    chainId: '222',
    blockExplorerUrls: 'https://crust.subscan.io',
  },
  {
    netWork: 'XDC',
    chainId: '50',
    symbol: 'XDC',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://rpc.xinfin.network',
    blockExplorerUrls: 'https://explorer.xinfin.network/',
  },
  {
    netWork: 'KLAY',
    chainId: '8217',
    symbol: 'KLAY',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://klaytn.mytokenpocket.vip',
    blockExplorerUrls: 'https://scope.klaytn.com',
  },
  {
    netWork: 'EOS',
    chainId: '1040',
    blockExplorerUrls: 'https://www.bloks.io',
  },
  {
    netWork: 'HPB',
    chainId: '269',
    symbol: 'HPB',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://hpbnode.com',
    blockExplorerUrls: 'https://hscan.org',
  },
  {
    netWork: 'CRONOS',
    chainId: '25',
    symbol: 'CRO',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://cronos-rpc.heavenswail.one',
    blockExplorerUrls: 'https://cronos.org/explorer',
  },
  {
    netWork: 'AME',
    chainId: '180',
    symbol: 'AME',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://node1.amechain.io/',
    blockExplorerUrls: 'https://amescan.io',
  },
  {
    netWork: 'ECH',
    chainId: '3000',
    symbol: 'ECH',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://draco.ech.network',
    blockExplorerUrls: 'https://scout.ech.network',
  },
  {
    netWork: 'CUBE',
    chainId: '1818',
    symbol: 'CUBE',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://http-mainnet.cube.network',
    blockExplorerUrls: 'https://www.cubescan.network',
  },
  {
    netWork: 'GNOSIS',
    chainId: '100',
    symbol: 'xDai',
    decimals: 18,
    gasLimit: 400000,
    rpcUrl: 'https://xdai-rpc.gateway.pokt.network',
    blockExplorerUrls: 'https://blockscout.com/poa/xdai',
  },
  {
    netWork: 'KSM',
    chainId: '',
  },

  {
    netWork: 'IOST',
    chainId: '',
  },
  {
    netWork: 'BNB',
    chainId: '',
  },
  {
    netWork: 'NFT',
    chainId: '10086',
  },
  {
    netWork: 'XRP',
    chainId: '1008600',
    blockExplorerUrls: 'https://xrpscan.com',
  },
]
